### ISSUE TITLE
How to insert caption to pictures?

### ISSUE THREAD

**Issue by AndreaIdini** [Scienza/SitoAndreaIdini#2]
Bisogna inserire caption alla figura in html.
Come lo metto in sotto un iframe?
cf. `/content/projects/physics/The nuclear physics.md` file l'iframe all'inizio del testo

**Comment by Pandry** [comment]
Should I reply in English or Italian?
Per quanto brutto, temo sia necessario inserire una tag HTML:
`<figcaption class="image-caption">Commento</figcaption>`
