### ISSUE TITLE
url links in wrong color

### ISSUE THREAD

**Issue by AndreaIdini** [Scienza/SitoAndreaIdini#4]
Nella sezione projects ci sono gli url di un colore che li rende illeggibili.

**Comment by Pandry** [comment]
![image](https://user-images.githubusercontent.com/17499836/42591726-d886e662-8547-11e8-9a8f-d0c0bc3ed14f.png)
Ti riferisci a questi link?

**Comment by AndreaIdini** [comment]
no, cliccaci sopra e guarda nel testo, ci sono delle parole scritte in bianco su sfondo bianco

**Comment by Pandry** [comment]
Intendi la sottolineatura?
![image](https://user-images.githubusercontent.com/17499836/43583628-51bd9228-9660-11e8-9b7d-ee7ad38650f0.png)
Comunque è assolutamente ma aggiustare

**Comment by AndreaIdini** [comment]
non avevo neanche realizzato.
All'interno degli articoli, gli url nella nuova versione appaiono bianchi.
Ti faccio lo screen quando torno al portatile

**Comment by Pandry** [comment]
Ah, ok...
Vedo se è una regola di CSS errata nel frattempo

**Comment by Pandry** [comment]
PR #9 approvata, chiudo
